---
version: '3.7'
services:
  mongo-server:
    build:
      context: mongo/
      args:
        MONGO_VERSION: ${MONGO_VERSION}
      dockerfile: Dockerfile
    restart: always
    container_name: "${CONTAINER_NAME}-mongo-server"
    volumes:
    - mongo-configdb:/data/configdb
    - mongo-data:/data/db
    - "./mongo/setup:/docker-entrypoint-initdb.d/"
    environment:
    - AUTH=yes
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    - APP_MONGO_HOST=${MONGO_HOST}
    - MONGO_PORT=27017
    ports:
    - "${MONGO_OUT_PORT}:27017"
volumes:
  mongo-configdb: 
  mongo-data: 
